import React, { useContext, useState } from 'react'
import Head from 'next/head'
import Sidebar from './Sidebar'
import {useRouter} from 'next/router'
import Alerta from './Alerta'
import { AlertaContext } from '../context/alertas/AlertaState'

const Layout = ({children}) => {
    const {pathname} = useRouter();
    const {error} = useContext(AlertaContext);

    return (
        <>
            <Head>
                <title>Next CRM 😛</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap" rel="stylesheet" />
            </Head>
            {error&&<Alerta />}
            {pathname === '/login' || pathname === '/registro'
                ?
                (
                    <div className='bg-blue-400 min-h-screen justify-center flex flex-col items-center bg-milthon bg-fixed bg-no-repeat'>
                        {children}
                    </div>
                )
                :
                <div className="h-screen flex">
                    <Sidebar>
                        {children}
                    </Sidebar>
                </div>
            }
        </>
    )
}

export default Layout
